spring:
  data:
    mongodb:
      # Use your local MongoDB URI for non-embedded operations
      uri: mongodb://localhost:27017/comparisondb
  mongodb:
    embedded:
      # Set the embedded MongoDB version to be used by Flapdoodle
      version: 4.0.12

logging:
  level:
    org.springframework: INFO
    com.example.comparison: DEBUG
